import React from 'react'

export default class Buttons extends React.Component {
    render(){
      return (
        <div className="buttons">
            <button
                className="jumbo"
                id="clear"
                onClick={this.props.clear}
                value="AC"
                >
                Clear
            </button>
            <button
                className="opperation"
                id="divide"
                onClick={this.props.operation}
                value="/"
                >
                /
            </button>
            <button
                className=""
                id="seven"
                onClick={this.props.number}
                value="7"
                >
                7
            </button>
            <button
                className=""
                id="eight"
                onClick={this.props.number}
                value="8"
                >
                8
            </button>
            <button
                className=""
                id="nine"
                onClick={this.props.number}
                value="9"
                >
                9
            </button>
            <button
                className="opperation"
                id="multiply"
                onClick={this.props.operation}
                value="*"
                >
                x
            </button>
            <button
                className=""
                id="four"
                onClick={this.props.number}
                value="4"
                >
                4
            </button>
            <button
                className=""
                id="five"
                onClick={this.props.number}
                value="5"
                >
                5
            </button>
            <button
                className=""
                id="six"
                onClick={this.props.number}
                value="6"
                >
                6
            </button>
            <button
                className="opperation"
                id="subtract"
                onClick={this.props.operation}
                value="-"
                >
                -
            </button>
            <button
                className=""
                id="one"
                onClick={this.props.number}
                value="1"
                >
                1
            </button>
            <button
                className=""
                id="two"
                onClick={this.props.number}
                value="2"
                >
                2
            </button>
            <button
                className=""
                id="three"
                onClick={this.props.number}
                value="3"
                >
                3
            </button>
            <button
                className="opperation"
                id="add"
                onClick={this.props.operation}
                value="+"
                >
                +
            </button>
            <button
                className=""
                id="zero"
                onClick={this.props.number}
                value="0"
                >
                0
            </button>
            <button
                className=""
                id="decimal"
                onClick={this.props.decimal}
                value="."
                >
                .
            </button>
            <button
                className=""
                id="equals"
                onClick={this.props.solve}
                value="="
                >
                =
            </button>
        </div>
      )
    }
  }